### ISSUE TITLE
How to further modify the generate model through GANspace

### ISSUE THREAD

**Issue by 0sure** [PeterWang512/GANSketching#20]
How can I use GANspace to adjust the image generated by the net_G? For example, the original generator can generate cats pictures indoor but I want the background to be outdoor grassland. Is such an operation possible? If possible, how can I operate through GANspace? Thank you very much for your help!

**Comment by PeterWang512** [comment]
Because GANSpace is an unsupervised method for latent direction, you'll need to manually check which layers and which principle component to use to achieve such edits. However, it is not guaranteed to find such operations. For more details, I would suggest reading the GANSpace paper and their code: https://github.com/harskish/ganspace

**Comment by 0sure** [comment]
> Because GANSpace is an unsupervised method for latent direction, you'll need to manually check which layers and which principle component to use to achieve such edits. However, it is not guaranteed to find such operations. For more details, I would suggest reading the GANSpace paper and their code: https://github.com/harskish/ganspace

Thanks for your replies and help! I'll check it out.
